### ISSUE TITLE
[Feature request] A way to mix creative CAD colorizer with another colorizer

### ISSUE THREAD

**Issue by gdavid04** [Kamefrede/rpsideas#32] opened 2019-01-24 19:26 UTC
You should be able to mix any CAD colorizer with the creative CAD colorizer. The mixed colorizer would have the color of the colorizer you mixed the creative colorizer with, but still have the properties of the creative colorizer. Maybe add a small brightness change over time like in the creative colorizer.

**Comment by Kamefrede** [comment] 2019-01-24 21:44
Duplicate of #29

**Closed by Kamefrede** 2019-01-24 21:44 UTC
